#include "UI/AFLW_HueArc.h"

#include "Cosmetics/AFLCosmeticSelectionTypes.h" // AFLCreatorGamut -- the track IS the gamut
#include "Rendering/DrawElements.h"
#include "Widgets/SLeafWidget.h"

#define LOCTEXT_NAMESPACE "AFLHueArc"

// ================================================================================================
// SAFLHueArc -- the native-painted control. First custom Slate paint in AFL (flagged in the kit
// report); the paint and the input share ONE geometry mapping so the handle can never sit where a
// click would not put it.
// ================================================================================================

class SAFLHueArc : public SLeafWidget
{
public:
	DECLARE_DELEGATE_OneParam(FOnHue, float);
	DECLARE_DELEGATE_TwoParams(FOnStop, FName, float);

	SLATE_BEGIN_ARGS(SAFLHueArc) {}
	SLATE_END_ARGS()

	void Construct(const FArguments& InArgs) {}

	// State pushed from the UWidget. Plain members: SynchronizeProperties re-pushes on any change.
	float HueDegrees = 0.0f;
	bool  bHasValue = false;
	bool  bReadOnly = false;
	bool  bDiscrete = false;
	TArray<FAFLHueArcStop> Stops;
	float ArcRadius = 62.0f;
	float Thickness = 12.0f;
	float SweepDegrees = 240.0f;
	int32 Segments = 48;
	FLinearColor AccentColor = FLinearColor(0.0186f, 0.1075f, 1.0f);

	FOnHue OnHueChanged;
	FOnHue OnCommitted;
	FOnStop OnStopPicked;

	virtual FVector2D ComputeDesiredSize(float) const override
	{
		// Ends of a 240-degree sweep dip below centre by sin(30) * R; leave room for the handle ticks.
		const float HandlePad = Thickness * 1.4f;
		return FVector2D(
			2.0f * (ArcRadius + HandlePad),
			ArcRadius + HandlePad + FMath::Sin(FMath::DegreesToRadians(FMath::Max(0.0f, (SweepDegrees - 180.0f) * 0.5f))) * ArcRadius + HandlePad);
	}

	virtual bool SupportsKeyboardFocus() const override { return !bReadOnly; }

	virtual int32 OnPaint(const FPaintArgs& Args, const FGeometry& AllottedGeometry,
		const FSlateRect& MyCullingRect, FSlateWindowElementList& OutDrawElements, int32 LayerId,
		const FWidgetStyle& InWidgetStyle, bool bParentEnabled) const override
	{
		const float Alpha = bReadOnly ? 0.35f : 1.0f;
		const float TrackAlpha = (bDiscrete ? 0.35f : 1.0f) * Alpha;

		// TRACK: segments generated by the same gamut function the server commits with.
		TArray<FVector2D> Pair;
		Pair.SetNum(2);
		for (int32 i = 0; i < Segments; ++i)
		{
			const float T0 = static_cast<float>(i) / Segments;
			const float T1 = static_cast<float>(i + 1) / Segments;
			Pair[0] = PointAt(AllottedGeometry, T0, 0.0f);
			Pair[1] = PointAt(AllottedGeometry, T1, 0.0f);
			FLinearColor Seg = AFLCreatorGamut::FromHue((T0 + T1) * 0.5f * 360.0f);
			Seg.A = TrackAlpha;
			FSlateDrawElement::MakeLines(OutDrawElements, LayerId, AllottedGeometry.ToPaintGeometry(),
				Pair, ESlateDrawEffect::None, Seg, true, Thickness);
		}

		// STOPS: radial ticks. Owned = solid at the SKU colour; unowned = dim outline (I-9).
		for (const FAFLHueArcStop& Stop : Stops)
		{
			const float T = FMath::Frac(Stop.HueDegrees / 360.0f);
			Pair[0] = PointAt(AllottedGeometry, T, -Thickness * 0.75f);
			Pair[1] = PointAt(AllottedGeometry, T, Thickness * 0.75f);
			FLinearColor TickColor = Stop.bOwned
				? AFLCreatorGamut::FromHue(Stop.HueDegrees)
				: FLinearColor(0.42f, 0.46f, 0.60f, 0.9f);
			TickColor.A *= Alpha;
			FSlateDrawElement::MakeLines(OutDrawElements, LayerId + 1, AllottedGeometry.ToPaintGeometry(),
				Pair, ESlateDrawEffect::None, TickColor, true, Stop.bOwned ? 4.0f : 2.0f);
			if (Stop.bOwned)
			{
				// White caps make ownership legible without colour (badge+label law: the WBP pairs a
				// label; the cap is the non-colour carrier at the control itself).
				Pair[0] = PointAt(AllottedGeometry, T, Thickness * 0.75f);
				Pair[1] = PointAt(AllottedGeometry, T, Thickness * 1.05f);
				FSlateDrawElement::MakeLines(OutDrawElements, LayerId + 1, AllottedGeometry.ToPaintGeometry(),
					Pair, ESlateDrawEffect::None, FLinearColor(0.91f, 0.93f, 0.97f, Alpha), true, 2.0f);
			}
		}

		// HANDLE: absent when no value (unset stays unset -- painting one would claim a pick).
		if (bHasValue)
		{
			const float T = FMath::Frac(HueDegrees / 360.0f);
			// Soft glow behind, then the white carrier, then the hue core.
			Pair[0] = PointAt(AllottedGeometry, T, -Thickness * 1.1f);
			Pair[1] = PointAt(AllottedGeometry, T, Thickness * 1.1f);
			FLinearColor Glow = AFLCreatorGamut::FromHue(HueDegrees);
			Glow.A = 0.35f * Alpha;
			FSlateDrawElement::MakeLines(OutDrawElements, LayerId + 2, AllottedGeometry.ToPaintGeometry(),
				Pair, ESlateDrawEffect::None, Glow, true, 9.0f);
			FSlateDrawElement::MakeLines(OutDrawElements, LayerId + 3, AllottedGeometry.ToPaintGeometry(),
				Pair, ESlateDrawEffect::None, FLinearColor(0.91f, 0.93f, 0.97f, Alpha), true, 5.0f);
			FLinearColor Core = AFLCreatorGamut::FromHue(HueDegrees);
			Core.A = Alpha;
			FSlateDrawElement::MakeLines(OutDrawElements, LayerId + 4, AllottedGeometry.ToPaintGeometry(),
				Pair, ESlateDrawEffect::None, Core, true, 2.5f);
		}

		// FOCUS RING: outer arc in the brand accent, gamepad-legible (CommonUI rule: focus always
		// visible). Drawn only while focused.
		if (HasKeyboardFocus())
		{
			TArray<FVector2D> Ring;
			Ring.Reserve(Segments + 1);
			for (int32 i = 0; i <= Segments; ++i)
			{
				Ring.Add(PointAt(AllottedGeometry, static_cast<float>(i) / Segments, Thickness * 1.25f));
			}
			FLinearColor RingColor = AccentColor;
			RingColor.A = 0.8f;
			FSlateDrawElement::MakeLines(OutDrawElements, LayerId + 5, AllottedGeometry.ToPaintGeometry(),
				Ring, ESlateDrawEffect::None, RingColor, true, 1.5f);
		}

		return LayerId + 6;
	}

	virtual FReply OnMouseButtonDown(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) override
	{
		if (bReadOnly || MouseEvent.GetEffectingButton() != EKeys::LeftMouseButton)
		{
			return FReply::Unhandled();
		}
		ApplyPointer(MyGeometry, MouseEvent);
		return FReply::Handled().CaptureMouse(SharedThis(this)).SetUserFocus(SharedThis(this), EFocusCause::Mouse);
	}

	virtual FReply OnMouseMove(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) override
	{
		if (!bReadOnly && HasMouseCapture())
		{
			ApplyPointer(MyGeometry, MouseEvent);
			return FReply::Handled();
		}
		return FReply::Unhandled();
	}

	virtual FReply OnMouseButtonUp(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) override
	{
		if (HasMouseCapture() && MouseEvent.GetEffectingButton() == EKeys::LeftMouseButton)
		{
			OnCommitted.ExecuteIfBound(HueDegrees);
			return FReply::Handled().ReleaseMouseCapture();
		}
		return FReply::Unhandled();
	}

	virtual FReply OnKeyDown(const FGeometry& MyGeometry, const FKeyEvent& KeyEvent) override
	{
		if (bReadOnly)
		{
			return FReply::Unhandled();
		}
		const FKey Key = KeyEvent.GetKey();
		const bool bPrev = (Key == EKeys::Left || Key == EKeys::Down || Key == EKeys::Gamepad_DPad_Left || Key == EKeys::Gamepad_DPad_Down);
		const bool bNext = (Key == EKeys::Right || Key == EKeys::Up || Key == EKeys::Gamepad_DPad_Right || Key == EKeys::Gamepad_DPad_Up);
		if (bPrev || bNext)
		{
			if (bDiscrete)
			{
				StepStop(bNext ? 1 : -1);
			}
			else
			{
				SetHueFromInput(FMath::Fmod(HueDegrees + (bNext ? 3.0f : -3.0f) + 360.0f, 360.0f));
			}
			return FReply::Handled();
		}
		if (Key == EKeys::Enter || Key == EKeys::SpaceBar || Key == EKeys::Virtual_Accept)
		{
			OnCommitted.ExecuteIfBound(HueDegrees);
			return FReply::Handled();
		}
		return FReply::Unhandled();
	}

private:
	/** t in [0,1] along the sweep -> pixel point at radial offset from the track centreline.
	 *  ONE mapping for paint AND input; apex at t=0.5, top of the widget. */
	FVector2D PointAt(const FGeometry& Geometry, float T, float RadialOffset) const
	{
		const FVector2D Size = Geometry.GetLocalSize();
		const float HandlePad = Thickness * 1.4f;
		const FVector2D Centre(Size.X * 0.5f, ArcRadius + HandlePad);
		const float PhiDeg = 90.0f + SweepDegrees * 0.5f - T * SweepDegrees; // math degrees, y-up
		const float Phi = FMath::DegreesToRadians(PhiDeg);
		const float R = ArcRadius + RadialOffset;
		return FVector2D(Centre.X + R * FMath::Cos(Phi), Centre.Y - R * FMath::Sin(Phi));
	}

	void ApplyPointer(const FGeometry& Geometry, const FPointerEvent& MouseEvent)
	{
		const FVector2D Local = Geometry.AbsoluteToLocal(MouseEvent.GetScreenSpacePosition());
		const FVector2D Size = Geometry.GetLocalSize();
		const float HandlePad = Thickness * 1.4f;
		const FVector2D Centre(Size.X * 0.5f, ArcRadius + HandlePad);
		const FVector2D V(Local.X - Centre.X, Centre.Y - Local.Y); // y-up
		const float PhiDeg = FMath::RadiansToDegrees(FMath::Atan2(V.Y, V.X));
		// Invert PhiDeg = 90 + Sweep/2 - t*Sweep, wrapped into [0,360). A pointer in the dead gap
		// under the arc snaps to the NEARER end -- without this, the left half of the gap read as
		// t past 1 and jumped the handle to the far end.
		float Delta = FMath::Fmod(90.0f + SweepDegrees * 0.5f - PhiDeg + 360.0f, 360.0f);
		if (Delta > SweepDegrees)
		{
			Delta = (Delta - SweepDegrees > (360.0f - SweepDegrees) * 0.5f) ? 0.0f : SweepDegrees;
		}
		const float T = FMath::Clamp(Delta / SweepDegrees, 0.0f, 1.0f);
		SetHueFromInput(T * 360.0f);
	}

	void SetHueFromInput(float NewHue)
	{
		if (bDiscrete)
		{
			SnapToNearestOwnedStop(NewHue);
			return;
		}
		bHasValue = true;
		HueDegrees = NewHue;
		OnHueChanged.ExecuteIfBound(HueDegrees);
	}

	void SnapToNearestOwnedStop(float TargetHue)
	{
		const FAFLHueArcStop* Best = nullptr;
		float BestDist = FLT_MAX;
		for (const FAFLHueArcStop& Stop : Stops)
		{
			if (!Stop.bOwned) { continue; }
			const float D = FMath::Abs(FMath::FindDeltaAngleDegrees(TargetHue, Stop.HueDegrees));
			if (D < BestDist)
			{
				BestDist = D;
				Best = &Stop;
			}
		}
		// NO OWNED STOPS = NO WRITE. Free player with nothing owned gets a visible-but-inert arc,
		// never a silent continuum fallback that the server would then reject.
		if (Best && (!bHasValue || !FMath::IsNearlyEqual(Best->HueDegrees, HueDegrees)))
		{
			bHasValue = true;
			HueDegrees = Best->HueDegrees;
			OnStopPicked.ExecuteIfBound(Best->CosmeticId, Best->HueDegrees);
		}
	}

	void StepStop(int32 Direction)
	{
		// Cycle owned stops in hue order.
		TArray<const FAFLHueArcStop*> Owned;
		for (const FAFLHueArcStop& Stop : Stops)
		{
			if (Stop.bOwned) { Owned.Add(&Stop); }
		}
		if (Owned.Num() == 0) { return; }
		Owned.Sort([](const FAFLHueArcStop& A, const FAFLHueArcStop& B) { return A.HueDegrees < B.HueDegrees; });
		int32 Index = 0;
		if (bHasValue)
		{
			for (int32 i = 0; i < Owned.Num(); ++i)
			{
				if (FMath::IsNearlyEqual(Owned[i]->HueDegrees, HueDegrees, 0.5f)) { Index = i; break; }
			}
			Index = (Index + Direction + Owned.Num()) % Owned.Num();
		}
		bHasValue = true;
		HueDegrees = Owned[Index]->HueDegrees;
		OnStopPicked.ExecuteIfBound(Owned[Index]->CosmeticId, Owned[Index]->HueDegrees);
	}
};

// ================================================================================================
// UAFLW_HueArc -- the UMG face.
// ================================================================================================

UAFLW_HueArc::UAFLW_HueArc()
{
	SetVisibilityInternal(ESlateVisibility::Visible);
}

TSharedRef<SWidget> UAFLW_HueArc::RebuildWidget()
{
	ArcWidget = SNew(SAFLHueArc);
	ArcWidget->OnHueChanged.BindUObject(this, &UAFLW_HueArc::HandleSlateHueChanged);
	ArcWidget->OnCommitted.BindUObject(this, &UAFLW_HueArc::HandleSlateCommitted);
	ArcWidget->OnStopPicked.BindUObject(this, &UAFLW_HueArc::HandleSlateStopPicked);
	return ArcWidget.ToSharedRef();
}

void UAFLW_HueArc::SynchronizeProperties()
{
	Super::SynchronizeProperties();
	if (ArcWidget.IsValid())
	{
		ArcWidget->HueDegrees = HueDegrees;
		ArcWidget->bHasValue = bHasValue;
		ArcWidget->bReadOnly = bReadOnly;
		ArcWidget->bDiscrete = bDiscreteMode;
		ArcWidget->Stops = Stops;
		ArcWidget->ArcRadius = ArcRadius;
		ArcWidget->Thickness = Thickness;
		ArcWidget->SweepDegrees = SweepDegrees;
		ArcWidget->Segments = FMath::Clamp(Segments, 12, 128);
		ArcWidget->AccentColor = AccentColor;
	}
}

void UAFLW_HueArc::ReleaseSlateResources(bool bReleaseChildren)
{
	Super::ReleaseSlateResources(bReleaseChildren);
	ArcWidget.Reset();
}

#if WITH_EDITOR
const FText UAFLW_HueArc::GetPaletteCategory()
{
	return LOCTEXT("PaletteCategory", "AFL Kit");
}
#endif

void UAFLW_HueArc::SetHue(const float InHueDegrees, const bool bInHasValue)
{
	HueDegrees = FMath::Fmod(FMath::Fmod(InHueDegrees, 360.0f) + 360.0f, 360.0f);
	bHasValue = bInHasValue;
	SynchronizeProperties();
}

void UAFLW_HueArc::SetStops(const TArray<FAFLHueArcStop>& InStops)
{
	Stops = InStops;
	SynchronizeProperties();
}

void UAFLW_HueArc::SetReadOnly(const bool bInReadOnly)
{
	bReadOnly = bInReadOnly;
	SynchronizeProperties();
}

void UAFLW_HueArc::SetDiscreteMode(const bool bInDiscrete)
{
	bDiscreteMode = bInDiscrete;
	SynchronizeProperties();
}

void UAFLW_HueArc::HandleSlateHueChanged(const float InHue)
{
	HueDegrees = InHue;
	bHasValue = true;
	OnHueChanged.Broadcast(InHue);
}

void UAFLW_HueArc::HandleSlateCommitted(const float InHue)
{
	OnHueCommitted.Broadcast(InHue);
}

void UAFLW_HueArc::HandleSlateStopPicked(const FName InId, const float InHue)
{
	HueDegrees = InHue;
	bHasValue = true;
	OnStopPicked.Broadcast(InId, InHue);
}

#undef LOCTEXT_NAMESPACE
