// AFL kit (C2, I-8/I-9/I-25): the clamped hue arc. The ONLY colour control the creator ships --
// no RGB sliders, no hex input, by ruling (the arc offers exactly the freedom that survives the
// server clamp; see AFLCreatorGamut in AFLCosmeticSelectionTypes.h).
//
// ENGINEERING NOTE (deviation from AFL-3220's "UCommonUserWidget", recorded): this is a UWidget +
// native-painted SLeafWidget pair -- the engine-canonical custom-control form (UImage/UProgressBar
// family). A UUserWidget with no tree has nothing to paint or size, and a material-driven brush
// would hang the control off bridge-authored material assets, which crash-hardened badly in this
// project. Native paint keeps the whole control in one compiled file. There is no prior AFL custom
// Slate paint; this is the first, flagged as such in the kit report.

#pragma once

#include "Components/Widget.h"
#include "AFLW_HueArc.generated.h"

class SAFLHueArc;

/** One discrete stop on the arc: a colour SKU pinned at its hue. Owned stops are snappable in
 *  discrete mode; unowned stops render hollow and refuse the snap (I-9). */
USTRUCT(BlueprintType)
struct FAFLHueArcStop
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	float HueDegrees = 0.0f;

	/** The catalog SKU this stop represents (discrete mode outputs the SKU, not just the hue). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	FName CosmeticId = NAME_None;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	bool bOwned = false;
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnAFLHueArcHueChanged, float, HueDegrees);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnAFLHueArcCommitted, float, HueDegrees);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnAFLHueArcStopPicked, FName, CosmeticId, float, HueDegrees);

/**
 * The hue arc control. Paints the reachable gamut as the track (every segment is generated by the
 * same AFLCreatorGamut the server commits with -- there is nowhere out-of-gamut to drag to), a
 * handle at the current hue, and the chroma stops. Mouse-drag, arrow/D-pad nudge, focus ring.
 *
 * DUMB ON PURPOSE: hue in, hue out. Clamping, linking, schema gating and preview all stay in
 * UAFLW_Creator::SetChannelHue / UAFLW_LoadoutBase::CreatorSetChannel -- the one clamp rule.
 */
UCLASS()
class AFLCOMBAT_API UAFLW_HueArc : public UWidget
{
	GENERATED_BODY()

public:
	UAFLW_HueArc();

	/** Live while dragging or nudging. Continuum mode only. */
	UPROPERTY(BlueprintAssignable, Category = "AFL|HueArc")
	FOnAFLHueArcHueChanged OnHueChanged;

	/** Pointer released / Enter pressed -- the "settled" signal for consumers that batch. */
	UPROPERTY(BlueprintAssignable, Category = "AFL|HueArc")
	FOnAFLHueArcCommitted OnHueCommitted;

	/** Discrete mode: an OWNED stop was picked. Carries the SKU (I-9: output is the SKU id). */
	UPROPERTY(BlueprintAssignable, Category = "AFL|HueArc")
	FOnAFLHueArcStopPicked OnStopPicked;

	/** Current hue + whether the channel has a value at all (no value = no handle, per the
	 *  unset-stays-unset rule on the rail). */
	UFUNCTION(BlueprintCallable, Category = "AFL|HueArc")
	void SetHue(float InHueDegrees, bool bInHasValue);

	UFUNCTION(BlueprintCallable, Category = "AFL|HueArc")
	void SetStops(const TArray<FAFLHueArcStop>& InStops);

	/** Lapsed-subscriber shape (I-9 lapse rule): colours stay, control locks. */
	UFUNCTION(BlueprintCallable, Category = "AFL|HueArc")
	void SetReadOnly(bool bInReadOnly);

	/** Free-player shape: input snaps to the nearest OWNED stop; the continuum dims. */
	UFUNCTION(BlueprintCallable, Category = "AFL|HueArc")
	void SetDiscreteMode(bool bInDiscrete);

	UFUNCTION(BlueprintPure, Category = "AFL|HueArc")
	float GetHueDegrees() const { return HueDegrees; }

	// -- Geometry / look. Defaults match the ratified mock (I-25). ------------------------------
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "AFL|HueArc")
	float ArcRadius = 62.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "AFL|HueArc")
	float Thickness = 12.0f;

	/** Degrees of arc the full hue circle maps onto. 240 = the mock's top arc. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "AFL|HueArc", meta = (ClampMin = "90", ClampMax = "330"))
	float SweepDegrees = 240.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "AFL|HueArc", meta = (ClampMin = "12", ClampMax = "128"))
	int32 Segments = 48;

	/** Focus ring colour. Brand accent #1E5AFF (I-24); a WBP may restyle but never to cyan. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "AFL|HueArc")
	FLinearColor AccentColor = FLinearColor(0.0186f, 0.1075f, 1.0f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	float HueDegrees = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	bool bHasValue = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	bool bReadOnly = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	bool bDiscreteMode = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AFL|HueArc")
	TArray<FAFLHueArcStop> Stops;

	//~UWidget
	virtual void SynchronizeProperties() override;
	virtual void ReleaseSlateResources(bool bReleaseChildren) override;
#if WITH_EDITOR
	virtual const FText GetPaletteCategory() override;
#endif

protected:
	virtual TSharedRef<SWidget> RebuildWidget() override;

private:
	// Slate -> UMG relays (the Slate widget knows nothing about UObjects).
	void HandleSlateHueChanged(float InHue);
	void HandleSlateCommitted(float InHue);
	void HandleSlateStopPicked(FName InId, float InHue);

	TSharedPtr<SAFLHueArc> ArcWidget;
};
