// CC-5.2 -- THE CREATOR WIDGET (C++ base). Behaviour and bindings only; the WBP child owns layout.
//
// WHY A ROW ARRAY AND NOT FOUR NAMED CONTROLS. The channel count is a PROPERTY OF THE CHASSIS, not of
// the screen: two on the X line (M_AFL_Character -- body is inert there), three on Manny-based masters.
// A widget with four fixed rows, two of them greyed, would present a chassis difference as a fault.
// So the rail is DATA: RefreshFromSchema() rebuilds an array from FAFLCreatorChannelSchema and the WBP
// binds a ListView to it. Nothing here hard-codes a rail length.
//
// WHY THE ARC CANNOT LEAVE THE GAMUT. The track is generated by AFLCreatorGamut::FromHue(), so every
// point on it is already clamped -- there is nowhere out-of-gamut to drag TO. That is the difference
// between a visible clamp and a snap-back, and a snap-back teaches the player the tool is fighting
// them. Saturation and value are NOT player-facing axes; we do not ship sliders for them and then
// clamp the result.
//
// ONE CLAMP, SHARED. Every colour leaves through UAFLW_LoadoutBase::CreatorSetChannel, which clamps on
// entry with the SAME AFLCreatorGamut functions the server commits with. A second clamp here would be
// a second implementation of one rule, and two implementations drift silently -- the player is shown
// one colour and given another.
#pragma once

#include "CommonActivatableWidget.h"
#include "Cosmetics/AFLCosmeticSelectionTypes.h"  // EAFLCreatorChannel, EAFLChannelAvailability, schema, gamut, links
#include "AFLW_Creator.generated.h"

class UAFLW_LoadoutBase;
class UAFLWalletComponent;

/**
 * One rail row. Everything the WBP needs to draw a channel WITHOUT re-deriving anything -- including
 * the reason text, because a disabled control with no reason is indistinguishable from a broken one.
 */
USTRUCT(BlueprintType)
struct FAFLCreatorChannelRow
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	EAFLCreatorChannel Channel = EAFLCreatorChannel::Body;

	/** Stable, position-independent identity. CVD REQUIREMENT: a channel is identified by LABEL and
	 *  POSITION and READOUT -- never by its colour. This product IS colour; roughly 8% of male players
	 *  cannot tell channels apart by hue. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FText Label;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	EAFLChannelAvailability State = EAFLChannelAvailability::Absent;

	/** Only Connected is interactive. PresentButInert and Absent BOTH render -- disabled, with a
	 *  reason, and visually distinct from each other (they have different futures: inert is restorable
	 *  by a material change, absent is not). */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bInteractive = false;

	/** Sourced from the schema's ResolvedFromMaster. Empty when Connected. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FText Reason;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FLinearColor Colour = FLinearColor::White;

	/** False = the channel has no chosen hue yet. The handle is ABSENT and the readout is a dash --
	 *  we do NOT pre-seed at hue 0, which would imply red was chosen when nothing was. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bHasValue = false;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	float HueDegrees = 0.0f;

	/** Hex AND HSV together -- settled by the wireframe state sheet. HSV names the axis the arc
	 *  actually moves and makes the clamp legible ("S is at the 0.55 floor"); hex is recognisable and
	 *  copy-pasteable. Mono/tabular in the WBP so digits do not jitter while dragging. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FText Readout;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bLinked = false;

	/** Connected on an UNAUDITED master means "present, and inertness unknown" -- not "measured to
	 *  render". The caveat travels with the row so the UI cannot present it as a measured claim. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bUnauditedCaveat = false;
};

/**
 * CC-5.2. Binds the shipped creator interface to a rail the WBP can draw.
 *
 * DOES NOT own the preview rig. UAFLW_LoadoutBase owns the display pawn, the SceneCapture2D and the
 * render target; this widget drives them through that object and never spawns a second one -- the
 * preview IS the product, and a second render path would reintroduce exactly the divergence the
 * "what you see is what spawns" rule forbids.
 */
UCLASS(Abstract)
class AFLCOMBAT_API UAFLW_Creator : public UCommonActivatableWidget
{
	GENERATED_BODY()

public:
	/** Bind to the loadout that owns the preview rig. Call before anything else. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void InitializeCreator(UAFLW_LoadoutBase* InLoadout);

	/** Rebuild the rail from the schema. Safe to call repeatedly; call on chassis change. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void RefreshFromSchema();

	/** The rail. Length varies by chassis -- bind a list, never a fixed stack. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	const TArray<FAFLCreatorChannelRow>& GetChannelRows() const { return Rows; }

	/** True once a schema has actually been resolved. FAILS CLOSED: until then the rail is empty and
	 *  the WBP shows a skeleton -- it must not guess channel names. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	bool IsSchemaResolved() const { return bSchemaResolved; }

	/** Drag handler. Hue in degrees; everything else is decided by the shared clamp. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void SetChannelHue(EAFLCreatorChannel Channel, float HueDegrees);

	/** The colour the arc TRACK should paint at this hue. Generated by the gamut, so the track IS the
	 *  reachable set and there is nothing out-of-gamut to drag to. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	FLinearColor GetArcTrackColour(float HueDegrees) const;

	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void SetChannelLinked(EAFLCreatorChannel Channel, bool bLinked);

	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	bool IsChannelLinked(EAFLCreatorChannel Channel) const;

	/** Rotate the preview. Mesh, not actor -- the capture is attached to the actor. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void RotatePreview(float DeltaYawDegrees);

	//~ Slot counter -------------------------------------------------------------------------------
	/** Saved builds occupied. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	int32 GetSlotsUsed() const;

	/** Baseline + purchased, ceiling-clamped. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	int32 GetSlotCap() const;

	/** "n / cap", mono in the WBP. Always visible -- the cap is a live constraint, not a save-time
	 *  surprise. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	FText GetSlotCounterText() const;

	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	bool IsAtSlotCap() const { return GetSlotsUsed() >= GetSlotCap(); }

	/** The master the schema resolved from. The WBP shows this beside the chassis so an unaudited
	 *  verdict is attributable. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	FName GetResolvedMaster() const { return Schema.ResolvedFromMaster; }

	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	bool IsMasterAudited() const { return Schema.bMasterAudited; }

protected:
	/** Slot ladder, PRICING_SSOT 5.1: 2 free, 5 League, 10 hard cap. Named constants rather than
	 *  literals at the use site so a price/tier change lands in one place. */
	static constexpr int32 SlotBaseline    = 2;
	static constexpr int32 SlotTierCeiling = 5;
	static constexpr int32 SlotHardCap     = 10;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	TArray<FAFLCreatorChannelRow> Rows;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	FAFLCreatorChannelSchema Schema;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	bool bSchemaResolved = false;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	TWeakObjectPtr<UAFLW_LoadoutBase> Loadout;

	/** Fired after the rail changes so the WBP can rebind without polling. */
	UFUNCTION(BlueprintImplementableEvent, Category = "AFL|Creator")
	void OnChannelRowsChanged();

private:
	EAFLChannelAvailability StateFor(EAFLCreatorChannel Channel) const;
	FLinearColor ColourFor(EAFLCreatorChannel Channel, bool& bOutHasValue) const;
	FText ReasonFor(EAFLCreatorChannel Channel, EAFLChannelAvailability State) const;
	static FText BuildReadout(const FLinearColor& C, bool bHasValue);
	UAFLWalletComponent* ResolveWallet() const;
};
