// CC-5.2 -- THE CREATOR WIDGET (C++ base). Behaviour and bindings only; the WBP child owns layout.
//
// WHY A ROW ARRAY AND NOT FOUR NAMED CONTROLS. The channel count is a PROPERTY OF THE CHASSIS, not of
// the screen: two on the X line (M_AFL_Character -- body is inert there), three on Manny-based masters.
// A widget with four fixed rows, two of them greyed, would present a chassis difference as a fault.
// So the rail is DATA: RefreshFromSchema() rebuilds an array from FAFLCreatorChannelSchema and the WBP
// binds a ListView to it. Nothing here hard-codes a rail length.
//
// WHY THE ARC CANNOT LEAVE THE GAMUT. The track is generated by AFLCreatorGamut::FromHue(), so every
// point on it is already clamped -- there is nowhere out-of-gamut to drag TO. That is the difference
// between a visible clamp and a snap-back, and a snap-back teaches the player the tool is fighting
// them. Saturation and value are NOT player-facing axes; we do not ship sliders for them and then
// clamp the result.
//
// ONE CLAMP, SHARED. Every colour leaves through UAFLW_LoadoutBase::CreatorSetChannel, which clamps on
// entry with the SAME AFLCreatorGamut functions the server commits with. A second clamp here would be
// a second implementation of one rule, and two implementations drift silently -- the player is shown
// one colour and given another.
#pragma once

#include "CommonActivatableWidget.h"
#include "Cosmetics/AFLCosmeticSelectionTypes.h"  // EAFLCreatorChannel, EAFLChannelAvailability, schema, gamut, links
#include "UI/AFLW_LoadoutTileBase.h"        // EAFLLoadoutAxis (FocusAxis)
#include "AFLW_Creator.generated.h"

class UAFLW_LoadoutBase;
class UAFLWalletComponent;

/**
 * One rail row. Everything the WBP needs to draw a channel WITHOUT re-deriving anything -- including
 * the reason text, because a disabled control with no reason is indistinguishable from a broken one.
 */
/**
 * THE TWO CHASSIS. Ruled 2026-08-27; there are exactly two and they have three names between them.
 *
 *   MANNY    SKM_Manny         / M_Mannequin       -- older docs call this the "Original line"
 *   PRO MOD  SKM_IRONICS_Blank / M_AFL_Character   -- older docs call this the "X line". FBIK blank base.
 *
 * "X" IS THE LEGACY NAME FOR PRO MOD -- one chassis, not two. Reading PROMOD_CHARACTER_SSOT 2 beside
 * CHARACTER_CREATOR_SSOT 7 suggests a third chassis only because they name this one differently.
 *
 * ⚠ AFL.Character.<Name>_X ids are CHARACTER-ERA LEGACY, a per-character variant marker from when the
 * game shipped named characters. They do NOT select a chassis. A first version of this enum swapped
 * that suffix and was wrong twice: it treated legacy variants as lines, and it offered Manny as a
 * destination when SSOT 7 defers it. The chassis is decided by the BODY BASE, never by an id suffix.
 */
UENUM(BlueprintType)
enum class EAFLChassisLine : uint8
{
	Manny  UMETA(DisplayName = "Manny"),
	ProMod UMETA(DisplayName = "Pro Mod")
};

USTRUCT(BlueprintType)
struct FAFLCreatorChannelRow
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	EAFLCreatorChannel Channel = EAFLCreatorChannel::Body;

	/** Stable, position-independent identity. CVD REQUIREMENT: a channel is identified by LABEL and
	 *  POSITION and READOUT -- never by its colour. This product IS colour; roughly 8% of male players
	 *  cannot tell channels apart by hue. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FText Label;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	EAFLChannelAvailability State = EAFLChannelAvailability::Absent;

	/**
	 * The chassis is already WEARING this colour, but the player has not chosen it.
	 *
	 * SEPARATE FROM bHasValue ON PURPOSE, and the separation is load-bearing. bHasValue gates the SAVE
	 * path -- CommitRowsToBuild skips rows without it so that "never touched" cannot be written out as
	 * "deliberately chose this". Seeding inherited colours into bHasValue would display correctly and
	 * silently turn every untouched channel into an explicit choice on the first save.
	 *
	 * So: DISPLAY reads (bHasValue || bInherited). COMMIT reads bHasValue alone, unchanged.
	 */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bInherited = false;

	/** Only Connected is interactive. PresentButInert and Absent BOTH render -- disabled, with a
	 *  reason, and visually distinct from each other (they have different futures: inert is restorable
	 *  by a material change, absent is not). */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bInteractive = false;

	/** Sourced from the schema's ResolvedFromMaster. Empty when Connected. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FText Reason;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FLinearColor Colour = FLinearColor::White;

	/** False = the channel has no chosen hue yet. The handle is ABSENT and the readout is a dash --
	 *  we do NOT pre-seed at hue 0, which would imply red was chosen when nothing was. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bHasValue = false;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	float HueDegrees = 0.0f;

	/** Hex AND HSV together -- settled by the wireframe state sheet. HSV names the axis the arc
	 *  actually moves and makes the clamp legible ("S is at the 0.55 floor"); hex is recognisable and
	 *  copy-pasteable. Mono/tabular in the WBP so digits do not jitter while dragging. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FText Readout;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bLinked = false;

	/** Connected on an UNAUDITED master means "present, and inertness unknown" -- not "measured to
	 *  render". The caveat travels with the row so the UI cannot present it as a measured claim. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	bool bUnauditedCaveat = false;
};

/**
 * CC-5.2. Binds the shipped creator interface to a rail the WBP can draw.
 *
 * DOES NOT own the preview rig. UAFLW_LoadoutBase owns the display pawn, the SceneCapture2D and the
 * render target; this widget drives them through that object and never spawns a second one -- the
 * preview IS the product, and a second render path would reintroduce exactly the divergence the
 * "what you see is what spawns" rule forbids.
 */
/** C2 kit: a row's live hue, re-broadcast with the row's channel attached so the creator can route
 *  it into SetChannelHue (the ONE write path) without the row knowing the creator. */
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnAFLRowHueChanged, EAFLCreatorChannel, Channel, float, HueDegrees);

/**
 * UAFLW_CreatorChannelRowBase -- the contract for one row of the creator's channel rail.
 *
 * It exists because WBP_AFL_CreatorChannelRow derived from plain UUserWidget, so there was no way to
 * hand a spawned row its data. One property in, one event out; the WBP owns every pixel.
 */
UCLASS(Abstract, BlueprintType)
class AFLCOMBAT_API UAFLW_CreatorChannelRowBase : public UUserWidget
{
	GENERATED_BODY()

public:
	/** The row this widget draws. Set by the creator immediately before OnRowDataSet fires. */
	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator|Row")
	FAFLCreatorChannelRow Row;

	/** Optional extra drawing. The native paint below runs FIRST and is what makes a row legible; this
	 *  exists so a WBP can add to it, not so it can be the only thing that does. */
	UFUNCTION(BlueprintImplementableEvent, Category = "AFL|Creator|Row")
	void OnRowDataSet();

	/** Store the row, paint it, then let Blueprint add to it. */
	void SetRowData(const FAFLCreatorChannelRow& InRow);

	// Names match WBP_AFL_CreatorChannelRow exactly -- READ from the asset, not guessed.
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UTextBlock> Row_Label;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UTextBlock> Row_Readout;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UTextBlock> Row_Reason;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UTextBlock> Row_StateBadge;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UImage> Row_Swatch;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UCheckBox> Row_LinkToggle;

	/** C2 kit (I-8, ratified I-25): the native hue arc. Optional -- a greybox row without one keeps
	 *  working; a kit row with one gets the drag/nudge control wired by SetRowData below. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UAFLW_HueArc> Row_HueArc;

	/** The creator binds this in RebuildChannelRows -> SetChannelHue. */
	UPROPERTY(BlueprintAssignable, Category = "AFL|Creator|Row")
	FOnAFLRowHueChanged OnRowHueChanged;

private:
	UFUNCTION()
	void HandleArcHueChanged(float HueDegrees);
};

UCLASS(Abstract)
class AFLCOMBAT_API UAFLW_Creator : public UCommonActivatableWidget
{
	GENERATED_BODY()

public:
	/** CC-5: THE CREATOR MUST BE ESCAPABLE.
	 *
	 *  It was not. It shipped with no close button, no back handling and no focus target, so opening it
	 *  from the loadout TRAPPED the player -- Escape did nothing and there was no control to click. That
	 *  was my error: I recorded that back/cancel "needs no code" because both widgets sit on the same
	 *  activatable stack. Sharing a stack makes the loadout SURVIVE underneath; it does not give the
	 *  widget on top any way to pop itself. CommonUI only routes the Back action to widgets that opt in.
	 *
	 *  Set in the constructor rather than on the WBP so it cannot be lost by a reparent or a redesign of
	 *  the visual layer -- which is exactly what is about to happen to this screen. */
	UAFLW_Creator();

	/** Without a focus target the input router logged "widget isn't focusable - focusing the game
	 *  viewport" and left the creator unreachable by keyboard/gamepad. Prefer the rail, as the market
	 *  prefers its list. */
	virtual UWidget* NativeGetDesiredFocusTarget() const override;

protected:
	virtual void NativeOnInitialized() override;

	/** An always-available way out that does not depend on keyboard focus routing. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UButton> CloseButton;

	/** The rail the channel rows are spawned into. Was a ListView, which cannot render USTRUCT rows. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UPanelWidget> ChannelRailContainer;

	// ===== CC-5 step 5: THE COMMIT PATH ===========================================================
	// Names match the greybox WBP exactly -- F_Save and E_BuildName were READ off the widget tree, not
	// guessed. Guessing a widget name is what left the creator with no focus target and trapped a
	// player twice.

	/** The commit button. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UButton> F_Save;

	/** The build's name. Validated server-side; a refused name refuses the whole save. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UEditableTextBox> E_BuildName;

	/** The slot readout. Name matches the greybox WBP exactly -- read, not guessed. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional))
	TObjectPtr<class UTextBlock> D_SlotCounter;

	// ===== REGION A -- CHASSIS PICKER (CC_UI_HANDOFF section 2) ====================================
	//
	// "Ordered first because it determines the channel rail's contents." The rail length varies by
	// chassis, so a picker placed after it would let a player choose from a list that is about to be
	// replaced.
	//
	// The picker and its two tiles are REQUIRED (BindWidget) as of the CC-E authoring pass -- the WBP
	// carries them and a compile without them is a broken screen, not a pending one. The label/reason
	// texts stay Optional: the code null-guards each, and a redesign may legitimately restyle them.

	/** Container for the two chassis tiles. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidget), Category = "AFL|Creator|A")
	TObjectPtr<class UPanelWidget> A_ChassisPicker;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidget), Category = "AFL|Creator|A")
	TObjectPtr<class UButton> A_ChassisManny;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidget), Category = "AFL|Creator|A")
	TObjectPtr<class UButton> A_ChassisProMod;

	/** Display face, ALL-CAPS -- section 3 reserves Orbitron for identity-carrying text. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "AFL|Creator|A")
	TObjectPtr<class UTextBlock> A_ChassisMannyLabel;

	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "AFL|Creator|A")
	TObjectPtr<class UTextBlock> A_ChassisProModLabel;

	/**
	 * Why a chassis cannot be chosen. Body face, sentence case.
	 *
	 * NEVER A DEAD TILE: the states table forbids a control that accepts a click and goes nowhere, so
	 * an unavailable chassis carries its reason exactly as a disabled channel row does.
	 */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "AFL|Creator|A")
	TObjectPtr<class UTextBlock> A_ChassisProModReason;

	/** Same treatment for the other line -- neither is hidden when unavailable. */
	UPROPERTY(BlueprintReadOnly, meta = (BindWidgetOptional), Category = "AFL|Creator|A")
	TObjectPtr<class UTextBlock> A_ChassisMannyReason;

	// ===== REGION B -- PREVIEW VIEWPORT ===========================================================
	//
	// "The PreviewRT render target. Largest element by area -- it is the product." (section 2)
	// CREATOR_SSOT section 5.3: the preview IS the product; a stand-in reads as bait-and-switch on the
	// first match load. So this binds the EXISTING capture on UAFLW_LoadoutBase rather than making a
	// second one.
	UPROPERTY(BlueprintReadOnly, meta = (BindWidget), Category = "AFL|Creator|B")
	TObjectPtr<class UImage> B_PreviewImage;

	// ===== REGION F -- COMMIT BAR, SECOND HALF ====================================================
	//
	// "UCommonButtonBase x2" -- save AND revert. Revert existed in the WBP and was never bound, so
	// CREATOR_SSOT section 5.3's "every choice reversible without loss" had no code behind it.
	UPROPERTY(BlueprintReadOnly, meta = (BindWidget), Category = "AFL|Creator|F")
	TObjectPtr<class UButton> F_Revert;

public:
	/** Point the chassis tiles at the current state: which is worn, which is available, and why not. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator|A")
	void RefreshChassisPicker();

	/** Bind the preview render target into region B. Safe to call repeatedly. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator|B")
	void RefreshPreviewViewport();

protected:
	UFUNCTION() void HandleChassisMannyClicked();
	UFUNCTION() void HandleChassisProModClicked();
	UFUNCTION() void HandleRevertClicked();

	/** Paint the counter from the authoritative set. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator|Slots")
	void RefreshSlotCounter();

	/**
	 * Which saved build this session is editing. INDEX_NONE = a NEW build, which is the only case the
	 * slot cap gates -- editing one you already hold is always allowed.
	 */
	UPROPERTY(BlueprintReadWrite, Category = "AFL|Creator|Build")
	int32 EditingIndex = INDEX_NONE;

public:
	// THE BUILD API IS PUBLIC. It sat in a protected block, which was fine while only the creator's own
	// Save button called it -- the loadout now opens the creator ON a build, so LoadBuild/BeginNewBuild
	// are called from outside. BlueprintCallable already implied an external caller; C++ access simply
	// had not caught up.
	/** Assemble the current rail state into a build. Rows without a value stay UNSET. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Build")
	FAFLCreatorBuild AssembleBuild() const;

	/**
	 * Open an EXISTING saved build for editing: push its channels into the working selection, point
	 * EditingIndex at it, and refresh the rail and the name field.
	 *
	 * The inverse of AssembleBuild, and the piece Edit Build could not work without -- EditingIndex
	 * existed and nothing ever filled the rail from it.
	 *
	 * Returns false with a logged reason when the index names no build.
	 */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator|Build")
	bool LoadBuild(int32 Index);

	/** Start a NEW build: EditingIndex = INDEX_NONE, which is the only case the slot cap gates. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator|Build")
	void BeginNewBuild();

	/**
	 * Submit to the server. Returns false and logs a REASON when it did not dispatch -- a commit button
	 * that silently does nothing is indistinguishable from one that is not wired, which is how the
	 * creator's missing close control survived to trap a player.
	 *
	 * Dispatching is NOT succeeding: the server re-checks the cap, the name and the lapse state, and any
	 * of them can still refuse.
	 */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator|Build")
	bool CommitBuild();

protected:
	/** One row widget per channel. Unset = nothing to spawn, and it says so rather than drawing nothing. */
	UPROPERTY(EditDefaultsOnly, Category = "AFL|Creator")
	TSubclassOf<UAFLW_CreatorChannelRowBase> ChannelRowClass;

	/** Rebuild the rail from Rows. Safe to call repeatedly. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void RebuildChannelRows();

	virtual void NativeOnActivated() override;

	UFUNCTION()
	void HandleCloseClicked();

	UFUNCTION()
	void HandleSaveClicked();

public:

public:
	/** Bind to the loadout that owns the preview rig. Call before anything else. */
	/**
	 * CC-5: which axis the creator opens focused on. Set by the opener BEFORE activation, which is why
	 * the entry uses PushWidgetToLayerStack's init hook rather than pushing then poking -- a widget that
	 * activates on one axis and jumps to another is a visible glitch, not a detail.
	 *
	 * Sticker and Accessory arrive here because they are ARRANGEMENT axes: the loadout cannot express
	 * them as a tile (one id per axis), so its dormant enum members become "open the creator here".
	 */
	UPROPERTY(BlueprintReadWrite, Category = "AFL|Creator")
	EAFLLoadoutAxis FocusAxis = EAFLLoadoutAxis::BodyColor;

	/** Whether FocusAxis MEANS anything. Without this there is no way to say "no axis": the enum has no
	 *  unset value, which is why the old BodyColor default silently focused a channel on every open. */
	UPROPERTY(BlueprintReadWrite, Category = "AFL|Creator")
	bool bHasFocusAxis = false;

	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void InitializeCreator(UAFLW_LoadoutBase* InLoadout);

	/** Rebuild the rail from the schema. Safe to call repeatedly; call on chassis change. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void RefreshFromSchema();

	/** The rail. Length varies by chassis -- bind a list, never a fixed stack. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	const TArray<FAFLCreatorChannelRow>& GetChannelRows() const { return Rows; }

	/** True once a schema has actually been resolved. FAILS CLOSED: until then the rail is empty and
	 *  the WBP shows a skeleton -- it must not guess channel names. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	bool IsSchemaResolved() const { return bSchemaResolved; }

	/** Drag handler. Hue in degrees; everything else is decided by the shared clamp. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void SetChannelHue(EAFLCreatorChannel Channel, float HueDegrees);

	/** C2 kit: a spawned row's arc moved. One-line route into SetChannelHue -- bound per row in
	 *  RebuildChannelRows, dynamic so the binding survives the WBP layer. */
	UFUNCTION()
	void HandleRowHueChanged(EAFLCreatorChannel Channel, float HueDegrees);

	/** The colour the arc TRACK should paint at this hue. Generated by the gamut, so the track IS the
	 *  reachable set and there is nothing out-of-gamut to drag to. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	FLinearColor GetArcTrackColour(float HueDegrees) const;

	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void SetChannelLinked(EAFLCreatorChannel Channel, bool bLinked);

	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	bool IsChannelLinked(EAFLCreatorChannel Channel) const;

	/** Rotate the preview. Mesh, not actor -- the capture is attached to the actor. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator")
	void RotatePreview(float DeltaYawDegrees);

#if !UE_BUILD_SHIPPING
	/** TEST ONLY. Build the rail from a SUPPLIED schema instead of the bound loadout's.
	 *
	 *  WHY THIS EXISTS. CreatorGetSchema() resolves against the loadout's DisplayPawn, so a probe that
	 *  constructs a loadout without opening it gets whatever material happens to be reachable -- one
	 *  run resolved to MID_MI_AFL_FaceMask_Pink_2 and reported all four channels Connected on an
	 *  UNAUDITED master. Every schema-dependent assertion then compared two values that came from the
	 *  same wrong source and "passed" while testing nothing.
	 *
	 *  Driving the REAL row builder with a KNOWN schema (DeriveFromMaterial on M_AFL_Character vs
	 *  M_Mannequin) makes "the rail varies by chassis" checkable on demand instead of dependent on
	 *  whatever the preview rig happened to have loaded. Compiled out of shipping. */
	void DebugBuildRowsFromSchema(const FAFLCreatorChannelSchema& InSchema);
#endif

	//~ Slot counter -------------------------------------------------------------------------------
	/** Saved builds occupied. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	int32 GetSlotsUsed() const;

	// ===== CHASSIS LINE (C2) ========================================================================
	//
	// SSOT 5.1 makes the line a first-class choice: Original and X are genuinely different products,
	// and the channel count differs between them, so presenting one as a variant of the other would
	// read the difference as a fault.

	/**
	 * The identity id that resolves to the SHARED PRO MOD BLANK BASE.
	 *
	 * ONE shared blank base, not a body per identity: the creator "produces a selection record over a
	 * generic chassis" (SSOT 1), so Pro Mod needs one base class, not six.
	 *
	 * EXPOSED RATHER THAN HARD-CODED, and left EMPTY by default, because the row does not exist yet:
	 * B_AFL_Robot_Chassis_X (which wears SKM_IRONICS_Blank) is REFERENCED by
	 * DA_AFL_CharacterPartMap but carries no identity key, so nothing can address it. Inventing an id
	 * here would produce a control that resolves to nothing -- the exact silent no-op this picker
	 * exists to avoid. Point this at the key once the map has one and the Pro Mod card lights up with
	 * no code change.
	 */
	UPROPERTY(EditDefaultsOnly, Category = "AFL|Creator|Chassis")
	FName ProModChassisIdentityId;

	/** Which chassis the pawn is WEARING -- read from the body mesh, not from an id. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Chassis")
	EAFLChassisLine GetCurrentChassisLine() const;

	/**
	 * Can the player move to @Line right now, and if not, WHY.
	 *
	 * NEVER A DEAD CONTROL. The X card is currently unavailable for a measured reason:
	 * DA_AFL_CharacterPartMap carries 33 identity keys and ZERO ending in _X, so an X id resolves to
	 * an empty body class and the pawn silently keeps its original chassis. The reason travels with
	 * the refusal so the card explains itself instead of looking broken, and it lights up on its own
	 * the moment the map gains _X entries -- no code change.
	 */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Chassis")
	bool IsChassisLineAvailable(EAFLChassisLine Line, FText& OutReason) const;

	/** Move the working selection to @Line, then re-derive the rail. False (and nothing changed) if
	 *  the line is unavailable -- the caller should be showing the reason rather than the control. */
	UFUNCTION(BlueprintCallable, Category = "AFL|Creator|Chassis")
	bool SelectChassisLine(EAFLChassisLine Line);

	/** Baseline + purchased, ceiling-clamped. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	int32 GetSlotCap() const;

	/** "n / cap", mono in the WBP. Always visible -- the cap is a live constraint, not a save-time
	 *  surprise. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	FText GetSlotCounterText() const;

	UFUNCTION(BlueprintPure, Category = "AFL|Creator|Slots")
	bool IsAtSlotCap() const { return GetSlotsUsed() >= GetSlotCap(); }

	/** The master the schema resolved from. The WBP shows this beside the chassis so an unaudited
	 *  verdict is attributable. */
	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	FName GetResolvedMaster() const { return Schema.ResolvedFromMaster; }

	UFUNCTION(BlueprintPure, Category = "AFL|Creator")
	bool IsMasterAudited() const { return Schema.bMasterAudited; }

protected:
	/** Slot ladder, PRICING_SSOT 5.1: 2 free, 5 League, 10 hard cap. Named constants rather than
	 *  literals at the use site so a price/tier change lands in one place. */
	static constexpr int32 SlotBaseline    = 2;
	static constexpr int32 SlotHardCap     = 10;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	TArray<FAFLCreatorChannelRow> Rows;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	FAFLCreatorChannelSchema Schema;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	bool bSchemaResolved = false;

	UPROPERTY(BlueprintReadOnly, Category = "AFL|Creator")
	TWeakObjectPtr<UAFLW_LoadoutBase> Loadout;

	/** Fired after the rail changes so the WBP can rebind without polling. */
	UFUNCTION(BlueprintImplementableEvent, Category = "AFL|Creator")
	void OnChannelRowsChanged();


private:
	/** The one row builder. RefreshFromSchema and the debug entry BOTH go through it, so the probe
	 *  exercises shipping code rather than a copy that could diverge from it. */
	void RebuildRows();
	EAFLChannelAvailability StateFor(EAFLCreatorChannel Channel) const;
	FLinearColor ColourFor(EAFLCreatorChannel Channel, bool& bOutHasValue) const;
	FText ReasonFor(EAFLCreatorChannel Channel, EAFLChannelAvailability State) const;
	static FText BuildReadout(const FLinearColor& C, bool bHasValue);
	UAFLWalletComponent* ResolveWallet() const;
};
